apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: hiteshwani29/book-frontend-svc:0de0916af0463667e08ca26eae0e1b1c2af907e8
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
