apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes: ["ReadWriteOnce"]
  storageClassName: mongo