apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
provisioner: k8s.io/minikube-hostpath
volumeBindingMode: Immediate 
reclaimPolicy: Retain