apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-svc
  template:
    metadata:
      labels:
        app: mongo-svc
    spec:
      containers:
        - name: mongo-svc
          image: mongo
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongo-pvc       