apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookapp-master
  namespace: argocd
spec:
  destination:
    namespace: book-app
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: deployment-yamls
    repoURL: https://github.com/hiteshwani29/bookApp-deploy
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true